### PR TITLE
Add file information to getKtFile IllegalArgumentException

### PR DESCRIPTION
**Pull request by nataliapeterwas**
This PR: https://github.com/LemonAppDev/konsist/pull/1259 with passed tests

### CODE REVIEW

**Comment by mrmans0n** [comment]
Just curious, why do the tests pass here and not in #1259? Could it be because of the github CI not being configured properly to run for forked repos contributions? Or something transient?

Thanks!

**Comment by nataliapeterwas** [comment]
> Just curious, why do the tests pass here and not in #1259? Could it be because of the github CI not being configured properly to run for forked repos contributions? Or something transient?
> 
> Thanks!

We're not sure yet - we're investigating what might have caused this. Can you tell me if you forked the repository for a Windows or macOS machine? Our theory is that we may not be changing paths between the two systems correctly.

**Comment by mrmans0n** [comment]
tbh I did it on GitHub's web UI directly, as it pretty straightforward 🤣

**Comment by nataliapeterwas** [comment]
Konsist `0.16.0` has been released! This release includes this improvement :)

**Pull request merged**
